### ISSUE TITLE
Training Data

### ISSUE THREAD

**Issue by iitzco** [JakeRenn/AI-Challenger-Keypoints-pytorch#4]
Hi Jake,

I've been trying to download the training dataset from the official website [here](https://challenger.ai/datasets/keypoint) but the link appears to be completely broken.

Is there a possibility for you to give me access to the dataset? Maybe you have it backed up in a cloud service and you could provide me some download links...

Thanks in advance and hope you can help me.

**Comment by iitzco** [comment]
Solved! Just tried **https** and it worked.

Original link was [this one](http://ai-challenger.ufile.ucloud.com.cn/ai_challenger_keypoint_train_20170909.zip?k=3678681a3077c6b1&t=1532809837)

**Comment by salihkaragoz** [comment]
You are awesome. Thank you for your posting.

**Comment by c1a1o1** [comment]
How to install your nms？ @iitzco
